remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Gabriela Rojas
description: Graduating May 2024 | Bachelor of Science in Software Engineering
